### ISSUE TITLE
选择文件在火狐、Safari浏览器无效

### ISSUE THREAD

**Issue by curry1511** [psygame/UnityWebGLKits#2]

**Comment by psygames** [comment]
好勒，正愁没事干，让我来解决一下~

**Comment by curry1511** [comment]
我试了好多方法都没用，头疼。

**Comment by psygames** [comment]
莫慌，让我操作一波

**Comment by psygames** [comment]
@curry1511 已修复此BUG，在这次提交中 [commit](https://github.com/psygame/UnityWebGLKits/commit/0cd711c66c19e74907f9f88bb4f50742f78faa2a)

**Comment by Bian-Sh** [comment]
> 好勒，正愁没事干，让我来解决一下~

别让你老板看到你工作不饱和
