### ISSUE TITLE
Excel

### ISSUE THREAD

**Issue by pnzpb** [psygame/UnityWebGLKits#5]
大佬，在OpenFile我读取了一个Excel表格的byte流之后，有没有什么思路读取excel里面的内容，我用NPOI 那些类的dll在Editor里面能玩，发布webgl版之后就报错了

**Comment by psygames** [comment]
找一个 js 的 excel 解析库，在js里面解析吧。

**Comment by psygames** [comment]
https://github.com/SheetJS/sheetjs
推荐这库
